apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
data:
  POSTGRES_DB: "taskmanagerdb"
  POSTGRES_USER: "postgres"
  Jwt__Issuer: "TaskManagerApi"
  Jwt__Audience: "TaskManagerClient"
  Jwt__ExpiryMinutes: "60"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"