apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
type: Opaque
data:
  POSTGRES_PASSWORD: Y2hhbmdlbWVfaW5fcHJvZHVjdGlvbg==
  Jwt__Key: Q2hhbmdlVGhpc1RvQVJhbmRvbVNlY3JldEtleU1pbmltdW0zMkNoYXJzTG9uZyE=
  ConnectionStrings__DefaultConnection: SG9zdD1kYjtQb3J0PTU0MzI7RGF0YWJhc2U9dGFza21hbmFnZXJkYjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1jaGFuZ2VtZV9pbl9wcm9kdWN0aW9u